### ISSUE TITLE
on summon pet

### ISSUE THREAD

**Issue by Tototi1** [ArtixAllMighty/Rpg-Addon-Beastmaster#7]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  LoadingPlugin (Reskillable-1.12.2-1.2.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  WTPlugin (WaitingTime-1.0.0.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.14-96.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 5/28/18 6:04 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at subaraki.beastmaster.entity.EntityBeastmasterPet.getLevel(EntityBeastmasterPet.java:381)
	at subaraki.beastmaster.entity.EntityBeastmasterPet.func_70631_g_(EntityBeastmasterPet.java:463)
	at net.minecraft.entity.EntityLiving.canSkipUpdate(EntityLiving.java:1652)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:370)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at subaraki.beastmaster.entity.EntityBeastmasterPet.getLevel(EntityBeastmasterPet.java:381)
	at subaraki.beastmaster.entity.EntityBeastmasterPet.func_70631_g_(EntityBeastmasterPet.java:463)
	at net.minecraft.entity.EntityLiving.canSkipUpdate(EntityLiving.java:1652)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:370)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: beastmaster:bull_pet (subaraki.beastmaster.entity.EntityPetBull)
	Entity ID: 447709
	Entity Name: Bull Pet
	Entity's Exact location: 84.00, 4.00, -122.00
	Entity's Block location: World: (84,4,-122), Chunk: (at 4,0,6 in 5,-8; contains blocks 80,0,-128 to 95,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Tototi1'/382685, l='MpServer', x=84.70, y=4.00, z=-121.06]]
	Chunk stats: MultiplayerChunkCache: 439, 439
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (126,4,-115), Chunk: (at 14,0,13 in 7,-8; contains blocks 112,0,-128 to 127,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 7140928 game time, 9687 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 85 total;
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 593830472 bytes (566 MB) / 2280951808 bytes (2175 MB) up to 3400794112 bytes (3243 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128m -Xmx3256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_C9 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                    | Source                                                       | Signature                                |
	|:------ |:------------------- |:-------------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2                     | minecraft.jar                                                | None                                     |
	| UCHIJA | mcp                 | 9.42                       | minecraft.jar                                                | None                                     |
	| UCHIJA | FML                 | 8.0.99.99                  | forge-1.12.2-14.23.2.2611.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.2.2611               | forge-1.12.2-14.23.2.2611.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | creativecoredummy   | 1.0.0                      | minecraft.jar                                                | None                                     |
	| UCHIJA | mercurius_updater   | 1.0                        | MercuriusUpdater-1.12.2.jar                                  | None                                     |
	| UCHIJA | attributefix        | 1.0.1                      | AttributeFix-1.12.2-1.0.1.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | quark               | r1.4-123                   | Quark-r1.4-123.jar                                           | None                                     |
	| UCHIJA | autoreglib          | 1.3-16                     | AutoRegLib-1.3-16.jar                                        | None                                     |
	| UCHIJA | crafttweaker        | 4.1.8                      | CraftTweaker2-1.12-4.1.8.jar                                 | None                                     |
	| UCHIJA | jei                 | 4.8.5.147                  | jei_1.12.2-4.8.5.147.jar                                     | None                                     |
	| UCHIJA | base                | 3.7.1                      | base-1.12.2-3.7.1.jar                                        | None                                     |
	| UCHIJA | subcommonlib        | 1.2.0.1                    | subcommonlib-sublib-1.12.2-1.2.0.4 (1).jar                   | None                                     |
	| UCHIJA | rpginventory        | 1.12.2                     | rpginventory-1.12-5.3.0.0.jar                                | None                                     |
	| UCHIJA | beastmaster         | $version                   | beastmaster-1.12.2-1.2.0.1.jar                               | None                                     |
	| UCHIJA | bma_addon           | 1.11.2 4.0.3.0             | bma_addon-1.12-4.1.0.3.jar                                   | None                                     |
	| UCHIJA | ctm                 | MC1.12-0.2.3.12            | CTM-MC1.12-0.2.3.12.jar                                      | None                                     |
	| UCHIJA | chisel              | MC1.12.2-0.2.0.31          | Chisel-MC1.12.2-0.2.0.31.jar                                 | None                                     |
	| UCHIJA | classiccombat       | 1.0.0                      | ClassicCombat-1.12-1.0.0.jar                                 | None                                     |
	| UCHIJA | contenttweaker      | 1.12.2-4.5.0               | ContentTweaker-1.12.2-4.5.0.jar                              | None                                     |
	| UCHIJA | extendedrenderer    | v1.0                       | coroutil-1.12.1-1.2.6.jar                                    | None                                     |
	| UCHIJA | coroutil            | 1.12.1-1.2.6               | coroutil-1.12.1-1.2.6.jar                                    | None                                     |
	| UCHIJA | configmod           | v1.0                       | coroutil-1.12.1-1.2.6.jar                                    | None                                     |
	| UCHIJA | corpsecomplex       | 1.0.2.2                    | corpsecomplex-1.12.2-1.0.2.2.jar                             | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJA | ctgui               | 1.0.0                      | CraftTweaker2-1.12-4.1.8.jar                                 | None                                     |
	| UCHIJA | crafttweakerjei     | 2.0.2                      | CraftTweaker2-1.12-4.1.8.jar                                 | None                                     |
	| UCHIJA | creativecore        | 1.9.9                      | CreativeCore_v1.9.22_mc1.12.2.jar                            | None                                     |
	| UCHIJA | custommainmenu      | 2.0.8                      | CustomMainMenu-MC1.12.2-2.0.8.jar                            | None                                     |
	| UCHIJA | customnpcs          | 1.12                       | CustomNPCs_1.12.2(13may18).jar                               | None                                     |
	| UCHIJA | ptrmodellib         | 1.0.2                      | PTRLib-1.0.2.jar                                             | None                                     |
	| UCHIJA | props               | 2.6.0                      | Decocraft-2.6.0_1.12.2.jar                                   | None                                     |
	| UCHIJA | defaultoptions      | 9.2.5                      | DefaultOptions_1.12.2-9.2.5.jar                              | None                                     |
	| UCHIJA | extraalchemy        | 0.3.8.4-release            | extraalchemy-0.3.8.4-release.jar                             | None                                     |
	| UCHIJA | lunatriuscore       | 1.2.0.42                   | LunatriusCore-1.12.2-1.2.0.42-universal.jar                  | None                                     |
	| UCHIJA | mapgadgets          | @VERSION@                  | Mapmaker's+Gadgets-1.2_for_1.12.x.jar                        | None                                     |
	| UCHIJA | mtrm                | 1.2.2.30                   | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar                   | None                                     |
	| UCHIJA | nbtedit             | 1.11.2-2.0.2               | NBTEdit-1.12-2.0.2.jar                                       | None                                     |
	| UCHIJA | playerrevive        | 1.0                        | PlayerRevive_v1.2.13_mc1.12.2.jar                            | None                                     |
	| UCHIJA | redstonepaste       | 1.7.5                      | redstonepaste-mc1.12-1.7.5.jar                               | None                                     |
	| UCHIJA | reskillable         | 1.12.2-GRADLE:BUILD        | Reskillable-1.12.2-1.2.2.jar                                 | None                                     |
	| UCHIJA | resourceloader      | 1.5.3                      | ResourceLoader-MC1.12.1-1.5.3.jar                            | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJA | silentlib           | 2.2.18                     | SilentLib-1.12-2.2.18-100.jar                                | None                                     |
	| UCHIJA | scalinghealth       | 1.3.14                     | ScalingHealth-1.12-1.3.14-96.jar                             | None                                     |
	| UCHIJA | schematica          | 1.8.0.169                  | Schematica-1.12.2-1.8.0.169-universal.jar                    | None                                     |
	| UCHIJA | sophisticatedwolves | 3.13.2                     | SophisticatedWolves-1.12.2-3.13.2.jar                        | None                                     |
	| UCHIJA | stackie             | 1.6.0.48                   | Stackie-1.12.2-1.6.0.48-universal.jar                        | None                                     |
	| UCHIJA | trade               | 1.0.4                      | trade-1.0.4.jar                                              | None                                     |
	| UCHIJA | trapcraft           | v2.4.3a                    | Trapcraft-1.12-v2.4.3a-universal.jar                         | None                                     |
	| UCHIJA | tsquare             | 1.0.7                      | tsquare_1.12.2-1.0.7.jar                                     | None                                     |
	| UCHIJA | umbralux            | 1.12.2                     | umbralux-1.12.2-2.1.0.2.jar                                  | None                                     |
	| UCHIJA | variedcommodities   | 1.12.2                     | VariedCommodities_1.12.2(06nov17).jar                        | None                                     |
	| UCHIJA | waitingtime         | 1.0.0                      | WaitingTime-1.0.0.jar                                        | 6919c86a9d8d117dbc520ba31378675eaae1c16a |
	| UCHIJA | waystones           | 4.0.42                     | Waystones_1.12.2-4.0.42.jar                                  | None                                     |
	| UCHIJA | weaponlevels        | 2.1.2                      | weaponlevels-2.1.2.jar                                       | None                                     |
	| UCHIJA | worldeditcuife2     | 2.1.2-mf-1.12-14.21.1.2387 | WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12-14.21.1.2387.jar | None                                     |
	| UCHIJA | xaerominimap        | 1.14                       | Xaeros_Minimap_FP1.14_Forge_1.12.jar                         | None                                     |
	| UCHIJA | zombieawareness     | 1.12.1-1.11.12             | zombieawareness-1.12.1-1.11.12.jar                           | None                                     |
	| UCHIJA | justthetips         | 1.12-1.0.1.1               | justthetips-1.12-1.0.1.1.jar                                 | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Reskillable-1.12.2-1.2.2.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
WTPlugin (WaitingTime-1.0.0.jar)
  com.blamejared.waitingtime.core.WTClassTransformer
SHLoadingPlugin (ScalingHealth-1.12-1.3.14-96.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.24' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.24, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ctp_1.2_MCv2.zip
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 21
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.24
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by AbsolemJackdaw** [comment]
ill see to it when updating.
the error is a peculiar one
the game gives a true / false value instead of a number when trying to get the pet level
